### ISSUE TITLE
XLS->next() always returns a blank (not empty) array.

### ISSUE THREAD

**Issue by Justicimo** [Janson-Leung/PHPExcel#3]
https://github.com/Janson-Leung/PHPExcel/blob/fdd830c14534e7570a78bb4ea3ee6abf3e4ce838/PHPExcelReader/PHPExcel/Reader/XLS.php#L85

Because the for($i) loop is always true at least once `$this->currentRow[$i]` is always an array with the value of array("") which is **not** an empty array.
Which also means that `PHPExcelReader->next()` will never return null when using an XLS file.

**Comment by Justicimo** [comment]
https://github.com/Justicimo/PHPExcel/commit/522b7ccd0edd85e259e5b4ebe1e4a4dda3427bca
Added a quick fix to my branch, let me know what you think and I'll create a quick PR.

**Comment by Janson-Leung** [comment]
You can upgrade to use version 2
