### ISSUE TITLE
in Excel5 ChangeSheet() always return true.

### ISSUE THREAD

**Issue by Justicimo** [Janson-Leung/PHPExcel#4]
https://github.com/Janson-Leung/PHPExcel/blob/fdd830c14534e7570a78bb4ea3ee6abf3e4ce838/PHPExcelReader/PHPExcel/Reader/Excel5.php#L191

`ChangeSheet()` Should be returning false in the case of invalid `$index` . This results in `ChangeSheet()` returning true even when there is no available sheet to read.

**Comment by Janson-Leung** [comment]
You can upgrade to use version 2
