### ISSUE TITLE
Definition of the "lastColumnLetter" is not correct.

### ISSUE THREAD

**Issue by helga-cheberakha** [Janson-Leung/PHPExcel#8]
https://github.com/Janson-Leung/PHPExcel/blob/07ddc15b44c1f3ee967ded35cffeab5fec49a215/src/Parser/Excel2007.php#L221

Excel2007 parser returns a wrong value of the "lastColumnLetter" if a sheet has more than 27 columns and columns with an index like "AH" are empty for latest rows.
I suggest that will be better to use condition like
```
if (strlen($columnLetter) > strlen($info['lastColumnLetter'])
    || (strlen($columnLetter) == strlen($info['lastColumnLetter']) && $columnLetter > $info['lastColumnLetter'])) {
    $info['lastColumnLetter'] = $columnLetter;
}
```

**Comment by Janson-Leung** [comment]
columnLetter can be directly compared
